version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: toggleapi-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: toggleapi_db
    ports:
      - "5432"
    restart: unless-stopped