services:
  postgres-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    ports:
      - "5432"

  toggleapi-app:
    image: toggleapi-image
    environment:
      DB_HOST: postgres-db
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB_NAME}
      REDIS_HOST: redis-cache
    depends_on:
      - postgres-db
      - redis-cache