spring:
  application:
    name: toggleapi
  datasource:
    # Sulla porta 5432 (default di Postgres) sul tuo computer
    url: jdbcql://localhost/toggleapi_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    # Diciamo a JPA (Hibernate) di stampare le query SQL in console
    show-sql: true

  flyway:
      # Diciamo a Flyway di non bloccarsi se il DB è vuoto alla prima partenza
    baseline-on-migrate: true
